// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKylqx8ehDH6vpVuszNAXwpeYGIsn2elQ',
    appId: '1:1067214043661:web:aa567890d79036ff9b3344',
    messagingSenderId: '1067214043661',
    projectId: 'authentication-cae16',
    authDomain: 'authentication-cae16.firebaseapp.com',
    databaseURL: 'https://authentication-cae16-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-cae16.appspot.com',
    measurementId: 'G-4M74E6DGB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uSBkBo7z0Y11fkfi7MbYmc3C8FHALto',
    appId: '1:1067214043661:android:efdbb86529e2a5ea9b3344',
    messagingSenderId: '1067214043661',
    projectId: 'authentication-cae16',
    databaseURL: 'https://authentication-cae16-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-cae16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEnZShg8te3HFghbBRwnbrJjqWIO-g-A',
    appId: '1:1067214043661:ios:6505fe8bb10f4eb89b3344',
    messagingSenderId: '1067214043661',
    projectId: 'authentication-cae16',
    databaseURL: 'https://authentication-cae16-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-cae16.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEnZShg8te3HFghbBRwnbrJjqWIO-g-A',
    appId: '1:1067214043661:ios:6b9ffe4987409d869b3344',
    messagingSenderId: '1067214043661',
    projectId: 'authentication-cae16',
    databaseURL: 'https://authentication-cae16-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-cae16.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
